// events.js

const ALERT = "ALERT";
const REFETCH_CHAT = "REFETCH_CHAT";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE";

const START_TYPEING = "START_TYPEING";
const STOP_TYPEING = "STOP_TYPEING";

module.exports = {
  ALERT,
  REFETCH_CHAT,
  NEW_ATTACHMENT,
  NEW_MESSAGE_ALERT,
  NEW_MESSAGE,
  NEW_REQUEST,
  START_TYPEING,
  STOP_TYPEING,
};
